### PR TITLE
Release 0.0.10

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot 

Hey, 0.0.10 have been published. Adds a bplist and markdown decoder, nicer help and lots of bug fixes.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by herbygillot** [comment]
Thank you @wader - `fq`'s port in MacPorts has been updated

**Comment by wader** [comment]
@herbygillot Great, thanks!

**Comment by thushan** [comment]
Verified working on Win10 via scoop.

**Comment by wader** [comment]
@dundee 👍 0.0.9 making good progress?

**Comment by dundee** [comment]
It's slow, but moving :smile: It should land this or the next week.

**Pull request merged**
