### PR TITLE
fq: Update version to 0.0.5

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun Hey, just published 0.0.5. 

There is now also a CHANGES.md if that is interesting to include in a distro package.

**Comment by thushan** [comment]
scoop packages have been automatically updated!

image

**Comment by wader** [comment]
@thushan 👍 scoop automatically looks for new releases? 🤖

**Comment by thushan** [comment]
Yeah one of the many benefits of using the `autoupdate` & `checkver` components which I enabled in the package for [autoupdating packages](https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html).

https://github.com/ScoopInstaller/Main/pull/3295/files#diff-890722ea8186dbf78c1a38b3c9964105e47fc4c6f85834aaa5ef488c6e019c52R17

Sometimes for breaking changes it's a bit fiddly, but `fq` is (right now) quite lightweight & being hosted on github, the bot can auto manage that (within 30m-2hrs) of you publishing!

**Comment by wader** [comment]
Nice. Im also big fan of auto or semiautomatic version updates, for fq i use my own thingy https://github.com/wader/bump for go modules and some other things

**Comment by thushan** [comment]
That's awesome, will look at bump!

**Pull request merged**
