### PR TITLE
fq: Release 0.6.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by thushan** [comment]
Scoop has  0.6.0 for Windows folks :) Well done all!

**Comment by wader** [comment]
@thushan Thanks 👍

**Comment by herbygillot** [comment]
Thank you @wader - MacPorts has been updated: https://ports.macports.org/port/fq/

**Comment by wader** [comment]
@herbygillot Great 👍

**Comment by siraben** [comment]
Updated on Nixpkgs.

**Pull request merged**
