### PR TITLE
fq: Release 0.1.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot

Hey just published 0.1.0. Adds a avi decoder, nicer raw bits/bytes format and other smaller update and bug fixes.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by danfe** [comment]
FreeBSD port already updated, thanks for the heads-up! :-)

**Comment by herbygillot** [comment]
Thank you @wader, just updated for MacPorts.

**Comment by siraben** [comment]
Thanks @wader, nixpkgs has been updated.

**Comment by thushan** [comment]
Thanks @wader, updated on scoop.

**Comment by wader** [comment]
@danfe @herbygillot @siraben @thushan 👍 thanks for taking care of distribution packaging!

**Pull request merged**
