### PR TITLE
fq: Release 0.11.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hey! I've just published version 0.11.0 that adds NES ROM and JPEG 2000 decode support, a bunch of jq language from gojq upstream and as always various other small fixes and improvements.

**Comment by orhun** [comment]
Arch package is updated, congrats on the new release!

**Comment by danfe** [comment]
FreeBSD port had been updated, thanks for the heads-up!

**Comment by herbygillot** [comment]
[MacPorts updated](https://ports.macports.org/port/fq/details/) - thank you @wader

**Comment by siraben** [comment]
Merged in Nixpkgs.

**Comment by thushan** [comment]
Amazing news!! Scoop was updated 8hrs ago and confirmed working on newest release. Thanks @wader 

image

**Pull request merged**
