### PR TITLE
fq: Release 0.4.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hey just published 0.4.0, adds tls decode/decryption, matroska/webm streaming support, raw ip pcap support and some bug fixes.

See CHANGES.md for changes.

**Comment by 0-wiz-0** [comment]
Thank you, I've updated the pkgsrc package!

**Comment by herbygillot** [comment]
+1, thank you @wader. MacPorts has been updated as well.

**Comment by orhun** [comment]
Arch package is updated as well. Thanks!

**Comment by wader** [comment]
@0-wiz-0 @herbygillot @orhun Great thanks!

**Comment by thesamesam** [comment]
Done in gentoo, thanks!

**Comment by thushan** [comment]
Boom on scoop. Thanks!

**Pull request merged**
