### PR TITLE
fq: Release 0.8.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hello people, just published 0.8.0. Adds caff, moc3 and opentimestamps decoders otherwise mostly minor improvements and fixes.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by herbygillot** [comment]
MacPorts is updated: https://ports.macports.org/port/fq/

Thanks @wader

**Comment by wader** [comment]
@herbygillot damn your fast 😄

**Comment by thushan** [comment]
You've set a high bar for us to meet now @herbygillot - and I have failed this time.

0.8.0 is on scoop and our servers seem to be  using it as of 4hrs ago.

**Comment by herbygillot** [comment]
> You've set a high bar for us to meet now @herbygillot - and I have failed this time.
> 
> 0.8.0 is on scoop and our servers seem to be  using it as of 4hrs ago.

😄 All good, it's not a competition - thank you for your work on Scoop 🙂

**Comment by danfe** [comment]
Thanks for another realease!  I've updated FreeBSD port.

**Comment by thesamesam** [comment]
Done for Gentoo, thanks!

**Pull request merged**
