### PR TITLE
fq: Release 0.5.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
👍  and thanks 😊  not much fancy stuff but there are some interesting stuff i'm working on like http, http2 and basic kaitai struct stupport, but can't make any promises when, work on fq is very motivation-driven :)

**Comment by herbygillot** [comment]
Thanks @wader; MacPorts has been [updated](https://ports.macports.org/port/fq/).

**Comment by thushan** [comment]
Awesome work, scoop has been updated & verified. Hope you left an Easter Egg!

**Comment by siraben** [comment]
@wader updated on Nixpkgs!

**Comment by wader** [comment]
@siraben 👍

**Comment by thesamesam** [comment]
Did Gentoo yesterday too. Thanks!

**Pull request merged**
