### PR TITLE
fq: Release 0.10.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hey! I've just pubished version 0.10.0 that adds leveldb and fit format support and as usual a bunch of smaller fixes and updates. See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for examples and details.

**Comment by orhun** [comment]
Arch package is updated! Congrats on the new release 🚀

**Comment by herbygillot** [comment]
Thanks @wader. We're now updated on MacPorts.

**Comment by danfe** [comment]
FreeBSD port had been updated, thank you.

**Comment by thushan** [comment]
Thanks @wader, had to wait a bit but scoop on Windows has been updated now.

**Comment by siraben** [comment]
Updated on Nixpkgs.

**Comment by wader** [comment]
Thanks everyone!

**Pull request merged**
