### PR TITLE
fq: Release 0.13.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hello! I've just published version 0.13.0 with some new decoders and some smaller fixes.

https://github.com/wader/fq/releases/tag/v0.13.0

**Comment by herbygillot** [comment]
MacPorts is update: https://github.com/macports/macports-ports/commit/2a98a6ee0134b12bf9865378f4138683dc14aef6

Thank you @wader

**Comment by orhun** [comment]
Updated on Arch Linux, wohoo

thanks for the new release!

**Comment by wader** [comment]
@herbygillot @orhun 🥳

**Comment by thushan** [comment]
Nicely done, updated in scoop for Windows.

**Comment by thesamesam** [comment]
Done, thanks!

**Pull request merged**
