### PR TITLE
fit: Add decoder

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@mlofjard Hey, i noticed you working on a FIT decoder, maybe this stalled PR could be of interest? feel free to copy or get inspiration from it! I just rebased it and made sure it still builds and decodes somewhat.

Don't remember how far i got and what were left to do, but i think it i was thinking about adding support to use some definition file from garmin to map ids in a nicer way. I guess either by embedding it or add an option to the decoder to load it externally somehow at decode time.

**Comment by mlofjard** [comment]
Hi @wader, yes it started as a fun weekend project after your FOSDEM talk, and then I found this PR a few days later. I'm currently exploring generating the definitions from Garmins long excel sheet, while also adding more value formatting functions for stuff like dates, coordinates and such.

**Comment by wader** [comment]
Aha I see, that sounds great. We can probably replace this PR with what your working on. Feel free to create a PR early even if things are hacky or broken if you want feedback or review

**Comment by wader** [comment]
@mlofjard Hej! i did a quite large refactor how formats and register some days ago. I rebased this PR with the new way of doing it, should hopefully for you be just a copy/paste of the init function.

**Comment by mlofjard** [comment]
@wader Nice. I've been dragged around on other stuff lately, but today I might have some time to finally get back into it. Will rebase my fork and try it out.

**Comment by wader** [comment]
@mlofjard No hurry, nice to hear your still interested

**Comment by wader** [comment]
@mlofjard Tja, was nice to meet you! hope you made some progress and feel free to open a PR even if the code is very WIP if you want feedback or discuss something

**Comment by mlofjard** [comment]
@wader Yeah, it was funny that we ended up at the same hotel this year. I actually got it working, and it reads all the example files from the SDK now (the ones with dynamic developer fields were the final headache). A PR has been made.

**Comment by wader** [comment]
> @wader Yeah, it was funny that we ended up at the same hotel this year. I actually got it working, and it reads all the example files from the SDK now (the ones with dynamic developer fields were the final headache). A PR has been made.

Yeap! feel i should have stayed and chatted a bit more :) sound like really good progress! mm i remember there were some quite tricky things in the spec to understand.

**Comment by wader** [comment]
Replaced by #863

**Comment by wader** [comment]
@mlofjard i noticed this PR has a test.fit test file... but don't remember were i got it from :(

**Pull request closed without merging**
