### PR TITLE
fq: Release 0.7.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hello people, just published 0.7.0. Adds LuaJIT bytecode decoder otherwise mostly small improvements and fixes.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by thushan** [comment]
Well done! Scoop has  got the update :)

**Comment by herbygillot** [comment]
Thank you. [MacPorts](https://ports.macports.org/port/fq/) has been updated.

**Comment by orhun** [comment]
Congrats on the new release, [Arch package](https://archlinux.org/packages/extra/x86_64/fq/) has been updated.

**Comment by thesamesam** [comment]
Done for Gentoo, thanks!

**Pull request merged**
