### PR TITLE
typpp

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by wader** [comment]
Hey! Long time no see, how are you?

**Comment by mathieu-aubin** [comment]
> Hey! Long time no see, how are you?

I'm okay brother, thanks for asking! Hope you are well and having a blast

**Comment by wader** [comment]
> I'm okay brother, thanks for asking! Hope you are well and having a blast

Good to hear! Im good, having some vacation but can't stay away from fq. Didn't expect a bit-reader smashed together with a quirky functional language would be this popular :)

**Comment by wader** [comment]
And forgot, happy new year!

**Comment by mathieu-aubin** [comment]
Did you ever use [Binwalk](https://github.com/ReFirmLabs/binwalk) by any chance? i'm not sure yet about  'f**you" (joke) as i havnt done much reading and using - enoug to catch typo but thats it...

**Comment by wader** [comment]
No haven't used it, only briefly read about it. Seems like a nice tool, looks to be focused at reversing and analyzing "unknown" binaries?
fq currently for me is focused on very detailed decoding and good query support, but the jq language has extraordinary combinatorial abilities which probably could be useful for reversing or more brute-force:ish things. I've already used fq to looks for false sync in flac and ogg files with great success. What you do is use some matching function to iterate matches and then for each match try to decode and then filter somehow, something like this `scan_toend([0xff,0xfb]) | mp3_frame | select(.side_info)` would look for possible mp3 frames inside a file.

Also already started to regret naming it fq :) maybe becuse i was so deep into jq which i pronounce yay-queue i thought fq will by mostly be pronounce eff-queue (which i like more than bq), maybe was wrong? :)

**Comment by mathieu-aubin** [comment]
hhahaa. No, no... all is fine ' its only a name, it'll get over it!

And my reason for asking is just what you hint at... some combination - at some poiny in time if need be - combine some of the power of educated guessing and forsensic-ish features to jq's doppelganger.

Could make for a very useful FU for many! hahahha couldnt resist!

**Comment by wader** [comment]
> hhahaa. No, no... all is fine ' its only a name, it'll get over it!

Hope so :)

> And my reason for asking is just what you hint at... some combination - at some poiny in time if need be - combine some of the power of educated guessing and forsensic-ish features to jq's doppelganger.
> 
> Could make for a very useful FU for many! hahahha couldnt resist!

Yeap i think so too but i have only brifly thought about it, focus so far has been mostly media stuff plus some random formats, some search functions, nice cli/repl and just make things actually work :) But it seems like some infosec and digital forensics ppl are staring the projects so will so what shows up.

**Pull request merged**
