### PR TITLE
Release 0.0.8

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
Still working on refactor out text serialization formats (yaml etc) from interp package and also make them into proper decoder formats so they can be probed and also be used other decoders.

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot Hey, 0.0.8 have been published.

Sorry for the delay, vacation, heat wave and big refactor for generics and text serialization formats happened. Hopefully more regular releases from now on.

Biggest user facing change is that fq now can decode and convert to/from some text serialization formats like yaml, xml, html, toml and csv and it also has gained some text encoding, hash functions and functions for working with URLs parts. The mp4 and matroska decoders got some nice bug fixes and improvement and the tcp decoder output was restructured a bit. Also there was a range decode bug fixed the probably fixes some decode error crashes.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by herbygillot** [comment]
Thanks @wader - `fq` is updated for MacPorts: https://ports.macports.org/port/fq/details/

**Comment by wader** [comment]
@tlehman do you know if there is someone to ping about the suse package?

**Comment by tlehman** [comment]
I'll find out, ETA tomorrow

**Comment by thushan** [comment]
scoop has it (tho it was delayed for some reason again), but verified 0.8 installs!

Heat up north, rains down south, crazy times! Stay safe.

**Comment by tlehman** [comment]
I talked to someone at SUSE today and they said the way to get it into OpenSUSE Tumbleweed is to submit it to Factory

**Comment by wader** [comment]
Ok thanks, i dont have any experince with suse myself. Any chance the original packager want to help keep the version updated?

**Pull request merged**
