### PR TITLE
fq: Release 0.9.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hello ppl! I've just released 0.9.0 with various decoder and interpreter fixes and improvments. See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for examples and details.

**Comment by orhun** [comment]
Congrats on the new release! Updated in the Arch repos 🚀

**Comment by herbygillot** [comment]
Thank you @wader. MacPorts [is updated](https://ports.macports.org/port/fq/).

**Comment by thushan** [comment]
Awesome, thanks @wader, `fq` has updated on scoop for Windows users.

image

Updated nicely too :D 🎉 

image

**Comment by wader** [comment]
@orhun @herbygillot @thushan Thanks!

**Comment by siraben** [comment]
Nixpkgs is updated, thanks.

**Comment by thesamesam** [comment]
Done for Gentoo, thanks!

**Pull request merged**
