### PR TITLE
fq: Release 0.2.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot

Hey just published 0.2.0, tzif and apple_bookmark decoders added, lots of cleanup and minor fixes, some renaming and some defaults changed

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for changes.

**Comment by orhun** [comment]
[fq](https://archlinux.org/packages/community/x86_64/fq/) is updated to `0.2.0` for Arch Linux 🐻

**Comment by herbygillot** [comment]
Thank you @wader - MacPorts is updated

**Comment by thushan** [comment]
Thanks & Congrats @wader, updated on scoop.

**Comment by siraben** [comment]
Thanks @wader, Nixpkgs has been updated. Have a great holiday!

**Comment by wader** [comment]
@siraben Thanks and same to you!

**Comment by dundee** [comment]
Debian package released.

**Comment by wader** [comment]
@dundee 🥳 Thanks! would be great to sync the package description with the one from the README for next version. Ill try to remember to remind about it

**Pull request merged**
