### PR TITLE
fq: Release 0.12.0

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun @herbygillot @thesamesam @0-wiz-0

Hey! I've just published version 0.12.0 that fixes a REPL readline issue, some improved JPEG decoding, otherwise mostly updates of golang and dependencies.

https://github.com/wader/fq/releases/tag/v0.12.0

**Comment by thushan** [comment]
Windows scoop for `fq` was updated.

image

**Comment by herbygillot** [comment]
MacPorts is updated: https://ports.macports.org/port/fq/

**Comment by wader** [comment]
@thushan @herbygillot Thanks! 🥳

**Comment by danfe** [comment]
FreeBSD port updated, thanks for the heads-up (as always).

**Pull request merged**
