### PR TITLE
fq: Update to version 0.0.6

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
Still WIP, let me know if there is something someone would like to add

**Comment by wader** [comment]
@dundee @siraben @thushan @danfe @mpanczyk @orhun Hello, 0.0.6 have been published 🎉 

Have been mostly focused on fixing and cleaning up the REPL and CLI usage. But @Akaame macho decoder was finally merged. Next release will probably be more focused on formats and decoder things.

See [CHANGES.md](https://github.com/wader/fq/blob/master/CHANGES.md) for change and also the project description have been polished a bit if you want to update it in some package description etc.

**Comment by herbygillot** [comment]
Thanks for the heads-up, @wader. `fq` has already been updated in MacPorts: https://ports.macports.org/port/fq/

**Comment by wader** [comment]
@thushan thanks, good to hear! do you build and try master builds at times? wonder if maybe -rc builds would be interesting at some point?

**Comment by thushan** [comment]
Ah the current team doesn't but not a bad idea! I did do builds for 0.0.5.

**Comment by wader** [comment]
@thushan Ok, i'm mostly worried about breaking windows as i'm not using it myself. Maybe first step could be to try get the expect-based CLI tests running on windows CI also.

**Comment by thushan** [comment]
@wader let me help you with that this week.

**Comment by wader** [comment]
That would be great. If you want to look into running expect here is the CI env it runs in https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

The expect test is done from here https://github.com/wader/fq/blob/master/Makefile#L24 using https://github.com/wader/fq/blob/master/pkg/cli/test.sh and https://github.com/wader/fq/blob/master/pkg/cli/test.exp. The shell script is helper around the expect script to be able to pass a fq binary to test and also to be silent on success and print log if not.

The windows image has make and bash so hopefully it is mostly about installing expect and then checking if expect.exe is in path?

**Comment by wader** [comment]
Maybe should starta new issue about it to not disturb people

**Comment by dundee** [comment]
0.0.6 just uploaded to Debian unstable.

**Comment by wader** [comment]
@dundee 👍 i saw that fq got added debian testing. Will the version in unstable end up in testing after a while until stable is released or how does that work?

**Comment by dundee** [comment]
Yes, it will migrate to testing in couple of days and then be released in stable someday.

**Comment by wader** [comment]
Great, thanks. Interesting to see how much debian is a gateway into other distros :) if you haven't seen repology before it's a nice tool to keep track of things https://repology.org/project/fq-inspect-binary-data/versions

**Comment by dundee** [comment]
Yes, Debian is used by many other distros as a base. 

It's also good to consider packaging for brew and snap.

**Comment by wader** [comment]
Yeap i have my own brew formula at least and i've looked into having an official one but got a bit stuck on something... also there seems to be an "fq" formula already so have to figure what they do about name conflicts.

For snap there an issue #98 with some ideas but has stalled a bit.

**Pull request merged**
